"""empty message

Revision ID: 38ce06aa42a7
Revises: 8e61cdc1be4d
Create Date: 2023-10-15 12:19:51.225875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ce06aa42a7'
down_revision = '8e61cdc1be4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('googleID', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('googleID')

    # ### end Alembic commands ###
