"""empty message

Revision ID: 62fc1a62c5c6
Revises: 
Create Date: 2023-10-25 13:41:58.320022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62fc1a62c5c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_prod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('googleID', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('codigo_postal', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('propiedades', sa.String(length=250), nullable=True),
    sa.Column('ingredientes_tec', sa.String(length=250), nullable=True),
    sa.Column('ingredientes_prin', sa.String(length=250), nullable=True),
    sa.Column('metodo_utilizacion', sa.String(length=250), nullable=True),
    sa.Column('tamanyo', sa.Integer(), nullable=True),
    sa.Column('medicion', sa.String(length=5), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('id_precio', sa.String(), nullable=True),
    sa.Column('id_tipo', sa.Integer(), nullable=True),
    sa.Column('url_img', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo'], ['tipo_prod.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrito',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prod'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_prod')
    )
    op.create_table('favorito',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_prod'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_prod')
    )
    op.create_table('pedido',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prod'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_prod')
    )
    op.create_table('pedido_local',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prod'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_prod')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_local')
    op.drop_table('pedido')
    op.drop_table('favorito')
    op.drop_table('carrito')
    op.drop_table('producto')
    op.drop_table('user')
    op.drop_table('tipo_prod')
    # ### end Alembic commands ###
